@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist 
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureC4Integration.puml
!includeurl AzurePuml/Web/AzureWebApp.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!include DEVICONS/angular.puml

SHOW_PERSON_OUTLINE()

Person_Ext(user, "Customer", "Person that can edit their address and other data")

Container_Boundary(c1, "System") {
  Container(apiwrapper, "API Viacep Wrapper", "Golang e Fiber", "Anti-corruption layer to provide a centralized service over zip", "AzureWebApp")
  Container(spa, "Single-Page App", "Angular", "Find and edit address", "angular")
  Container(apibar, "API Bar", "Java and SpringBoot", "", "AzureWebApp")
  Container(apifoo, "API Foo", "C# and ASP.NET Core", "", "AzureWebApp")
}

System_Ext(apiviacep, "API ViaCEP", "zipcode provider service", "AzureWebApp")

Rel(user, spa, "Read content of", "https")
Rel(spa, apiwrapper, "Consume", "https/json")
Rel(apifoo, apiwrapper, "Consume", "https/json")
Rel(apibar, apiwrapper, "Consume", "https/json")
Rel(apiwrapper, apiviacep, "Consume", "https/json")

Lay_R(spa,apibar)
@enduml